/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const upperlimit: string;
declare const middlelimit: string;
declare const lowerlimit: string;

export { upperlimit, middlelimit, lowerlimit };

declare const __default_export__: {
  upperlimit: typeof upperlimit;
  middlelimit: typeof middlelimit;
  lowerlimit: typeof lowerlimit;
};
export default __default_export__;
