/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const utilsButton: string;
declare const comein: string;
declare const utilsImage: string;
declare const image: string;

export {
	container,
	utilsButton,
	comein,
	utilsImage,
	image
};

declare const __default_export__: {
	container: typeof container;
	utilsButton: typeof utilsButton;
	comein: typeof comein;
	utilsImage: typeof utilsImage;
	image: typeof image;
};
export default __default_export__;
