/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const langButton: string;
declare const fades: string;

export {
	langButton,
	fades
};

declare const __default_export__: {
	langButton: typeof langButton;
	fades: typeof fades;
};
export default __default_export__;
