/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const image: string;
declare const trackerHolder: string;
declare const tracker: string;

export { container, image, trackerHolder, tracker };

declare const __default_export__: {
  container: typeof container;
  image: typeof image;
  trackerHolder: typeof trackerHolder;
  tracker: typeof tracker;
};
export default __default_export__;
