/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const upperlimit: string;
declare const middlelimit: string;

export { container, upperlimit, middlelimit };

declare const __default_export__: {
  container: typeof container;
  upperlimit: typeof upperlimit;
  middlelimit: typeof middlelimit;
};
export default __default_export__;
