/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const cancelButton: string;

export {
	cancelButton
};

declare const __default_export__: {
	cancelButton: typeof cancelButton;
};
export default __default_export__;
