/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const middlelimit: string;
declare const link: string;

export {
	container,
	middlelimit,
	link
};

declare const __default_export__: {
	container: typeof container;
	middlelimit: typeof middlelimit;
	link: typeof link;
};
export default __default_export__;
