/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const limit: string;
declare const loader: string;
declare const l3: string;

export { container, limit, loader, l3 };

declare const __default_export__: {
  container: typeof container;
  limit: typeof limit;
  loader: typeof loader;
  l3: typeof l3;
};
export default __default_export__;
