/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const topcontainer: string;
declare const topguide: string;
declare const fade: string;
declare const bottomcontainer: string;
declare const bottomguide: string;
declare const image: string;

export {
	topcontainer,
	topguide,
	fade,
	bottomcontainer,
	bottomguide,
	image
};

declare const __default_export__: {
	topcontainer: typeof topcontainer;
	topguide: typeof topguide;
	fade: typeof fade;
	bottomcontainer: typeof bottomcontainer;
	bottomguide: typeof bottomguide;
	image: typeof image;
};
export default __default_export__;
