/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const settingButton: string;
declare const comein: string;
declare const settingImage: string;
declare const image: string;

export { container, settingButton, comein, settingImage, image };

declare const __default_export__: {
  container: typeof container;
  settingButton: typeof settingButton;
  comein: typeof comein;
  settingImage: typeof settingImage;
  image: typeof image;
};
export default __default_export__;
