/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const toast: string;
declare const limit: string;

export { container, toast, limit };

declare const __default_export__: {
  container: typeof container;
  toast: typeof toast;
  limit: typeof limit;
};
export default __default_export__;
