/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const customcursor: string;
declare const blink: string;
declare const middlelimit: string;
declare const lowerlimit: string;
declare const hide: string;

export { container, customcursor, blink, middlelimit, lowerlimit, hide };

declare const __default_export__: {
  container: typeof container;
  customcursor: typeof customcursor;
  blink: typeof blink;
  middlelimit: typeof middlelimit;
  lowerlimit: typeof lowerlimit;
  hide: typeof hide;
};
export default __default_export__;
