/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const inputError: string;
declare const shakeError: string;

export {
	container,
	inputError,
	shakeError
};

declare const __default_export__: {
	container: typeof container;
	inputError: typeof inputError;
	shakeError: typeof shakeError;
};
export default __default_export__;
