/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const modeButton: string;
declare const fades: string;

export { modeButton, fades };

declare const __default_export__: {
  modeButton: typeof modeButton;
  fades: typeof fades;
};
export default __default_export__;
