/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const ip: string;

export {
	container,
	ip
};

declare const __default_export__: {
	container: typeof container;
	ip: typeof ip;
};
export default __default_export__;
