/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const limit: string;
declare const info: string;
declare const marquee: string;
declare const marqueeMove: string;

export {
	container,
	limit,
	info,
	marquee,
	marqueeMove
};

declare const __default_export__: {
	container: typeof container;
	limit: typeof limit;
	info: typeof info;
	marquee: typeof marquee;
	marqueeMove: typeof marqueeMove;
};
export default __default_export__;
