/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const error: string;
declare const success: string;

export {
	container,
	error,
	success
};

declare const __default_export__: {
	container: typeof container;
	error: typeof error;
	success: typeof success;
};
export default __default_export__;
