/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const limit: string;

export {
	container,
	limit
};

declare const __default_export__: {
	container: typeof container;
	limit: typeof limit;
};
export default __default_export__;
