/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const container: string;
declare const middlelimit: string;
declare const imageHolder: string;
declare const float: string;
declare const image: string;
declare const lowerlimit: string;

export {
	container,
	middlelimit,
	imageHolder,
	float,
	image,
	lowerlimit
};

declare const __default_export__: {
	container: typeof container;
	middlelimit: typeof middlelimit;
	imageHolder: typeof imageHolder;
	float: typeof float;
	image: typeof image;
	lowerlimit: typeof lowerlimit;
};
export default __default_export__;
