/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as GoatIndexRouteImport } from './routes/goat/index'
import { Route as GoatIpAddressIndexRouteImport } from './routes/goat/ip-address/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoatIndexRoute = GoatIndexRouteImport.update({
  id: '/goat/',
  path: '/goat/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoatIpAddressIndexRoute = GoatIpAddressIndexRouteImport.update({
  id: '/goat/ip-address/',
  path: '/goat/ip-address/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goat/': typeof GoatIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/goat/ip-address/': typeof GoatIpAddressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goat': typeof GoatIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/goat/ip-address': typeof GoatIpAddressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goat/': typeof GoatIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/goat/ip-address/': typeof GoatIpAddressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goat/' | '/privacy/' | '/goat/ip-address/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goat' | '/privacy' | '/goat/ip-address'
  id: '__root__' | '/' | '/goat/' | '/privacy/' | '/goat/ip-address/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoatIndexRoute: typeof GoatIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  GoatIpAddressIndexRoute: typeof GoatIpAddressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goat/': {
      id: '/goat/'
      path: '/goat'
      fullPath: '/goat/'
      preLoaderRoute: typeof GoatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goat/ip-address/': {
      id: '/goat/ip-address/'
      path: '/goat/ip-address'
      fullPath: '/goat/ip-address/'
      preLoaderRoute: typeof GoatIpAddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoatIndexRoute: GoatIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  GoatIpAddressIndexRoute: GoatIpAddressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
