/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const upperlimit: string;
declare const middlelimit: string;
declare const imageHolder: string;
declare const image: string;
declare const lowerlimit: string;

export {
	upperlimit,
	middlelimit,
	imageHolder,
	image,
	lowerlimit
};

declare const __default_export__: {
	upperlimit: typeof upperlimit;
	middlelimit: typeof middlelimit;
	imageHolder: typeof imageHolder;
	image: typeof image;
	lowerlimit: typeof lowerlimit;
};
export default __default_export__;
