/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const ipButton: string;
declare const fades: string;

export {
	ipButton,
	fades
};

declare const __default_export__: {
	ipButton: typeof ipButton;
	fades: typeof fades;
};
export default __default_export__;
